import type { FieldDescriptor, ResourceDescriptor } from '../types';

const variableId: FieldDescriptor = {
	displayName: 'Variable ID',
	name: 'variableId',
	type: 'string',
	default: '',
	in: 'path',
	description: 'The account variable ID',
	required: true,
};

export const accountVariable: ResourceDescriptor = {
	value: 'accountVariable',
	name: 'Account Variable',
	description: 'Datto RMM account-level variables. Inherited by sites unless overridden by a same-name site variable.',
	fields: [],
	operations: [
		{
			value: 'getAll',
			name: 'Get Many',
			action: 'Get many account variables',
			description: 'List all account-level variables',
			method: 'GET',
			endpoint: '/api/v2/account/variables',
			shape: 'list',
			listKey: 'variables',
		},
		{
			value: 'get',
			name: 'Get',
			action: 'Get an account variable',
			description: 'Retrieve a single account variable by ID',
			method: 'GET',
			endpoint: '/api/v2/account/variable/{variableId}',
			shape: 'object',
			fields: [variableId],
		},
		{
			value: 'create',
			name: 'Create',
			action: 'Create an account variable',
			description: 'Create a new account-level variable',
			method: 'PUT',
			endpoint: '/api/v2/account/variable',
			shape: 'object',
			fields: [
				{
					displayName: 'Name',
					name: 'name',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'Variable name',
				},
				{
					displayName: 'Value',
					name: 'value',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'Variable value (up to 20,000 characters)',
				},
				{
					displayName: 'Masked (Hidden in UI)',
					name: 'masked',
					type: 'boolean',
					in: 'body',
					default: false,
					description: 'Whether to mask the value in the Datto RMM UI',
				},
			],
		},
		{
			value: 'update',
			name: 'Update',
			action: 'Update an account variable',
			description: 'Update an existing account variable by ID',
			method: 'POST',
			endpoint: '/api/v2/account/variable/{variableId}',
			shape: 'object',
			fields: [
				variableId,
				{ displayName: 'Name', name: 'name', type: 'string',
																																									default: '', in: 'body', description: 'New name' },
				{ displayName: 'Value', name: 'value', type: 'string',
																																											default: '', in: 'body', description: 'New value' },
				{
					displayName: 'Masked (Hidden in UI)',
					name: 'masked',
					type: 'boolean',
					in: 'body',
					default: false,
					description: 'Whether to mask the value in the UI',
				},
			],
		},
		{
			value: 'delete',
			name: 'Delete',
			action: 'Delete an account variable',
			description: 'Delete an account variable by ID',
			method: 'DELETE',
			endpoint: '/api/v2/account/variable/{variableId}',
			shape: 'action',
			fields: [variableId],
		},
	],
};
