import type { ResourceDescriptor } from '../types';

export const account: ResourceDescriptor = {
	value: 'account',
	name: 'Account',
	description: 'The Datto RMM account (your provider tenant) — variables, components, sites, users',
	fields: [],
	operations: [
		{
			value: 'get',
			name: 'Get',
			action: 'Get the account',
			description:
				'Retrieve the current Datto RMM account (provider tenant) — name, regional API URL, totals',
			method: 'GET',
			endpoint: '/api/v2/account',
			shape: 'object',
		},
		{
			value: 'getSites',
			name: 'Get Sites',
			action: 'Get many sites under the account',
			description: 'List all sites (customers) under this account. Supports pagination + name filter.',
			method: 'GET',
			endpoint: '/api/v2/account/sites',
			shape: 'paginated',
			listKey: 'sites',
		},
		{
			value: 'getDevices',
			name: 'Get Devices',
			action: 'Get many devices under the account',
			description: 'List all devices across all sites under this account. Use site-scoped Device → Get Many for a single site.',
			method: 'GET',
			endpoint: '/api/v2/account/devices',
			shape: 'paginated',
			listKey: 'devices',
		},
		{
			value: 'getComponents',
			name: 'Get Components',
			action: 'Get many components in the account',
			description:
				'List all components (scripts, monitors, applications) available in the Component Library',
			method: 'GET',
			endpoint: '/api/v2/account/components',
			shape: 'paginated',
			listKey: 'components',
		},
		{
			value: 'getUsers',
			name: 'Get Users',
			action: 'Get many users in the account',
			description: 'List all users (operators) in the Datto RMM account',
			method: 'GET',
			endpoint: '/api/v2/account/users',
			shape: 'paginated',
			listKey: 'users',
		},
		{
			value: 'getVariables',
			name: 'Get Variables',
			action: 'Get account-level variables',
			description: 'List the account-level variables. These are inherited by sites unless overridden by a same-name site variable.',
			method: 'GET',
			endpoint: '/api/v2/account/variables',
			shape: 'list',
			listKey: 'variables',
		},
		{
			value: 'getOpenAlerts',
			name: 'Get Open Alerts',
			action: 'Get open alerts across the account',
			description: 'List all currently-open alerts across every site',
			method: 'GET',
			endpoint: '/api/v2/account/alerts/open',
			shape: 'paginated',
			listKey: 'alerts',
		},
		{
			value: 'getResolvedAlerts',
			name: 'Get Resolved Alerts',
			action: 'Get resolved alerts across the account',
			description: 'List recently-resolved alerts across every site',
			method: 'GET',
			endpoint: '/api/v2/account/alerts/resolved',
			shape: 'paginated',
			listKey: 'alerts',
		},
	],
};
