import type { FieldDescriptor, ResourceDescriptor } from '../types';

const deviceUid: FieldDescriptor = {
	displayName: 'Device UID',
	name: 'deviceUid',
	type: 'string',
	default: '',
	in: 'path',
	description: 'The Datto RMM device UID (UUID). Use Device → Get By Hostname if you only have the hostname.',
	required: true,
};

export const device: ResourceDescriptor = {
	value: 'device',
	name: 'Device',
	description: 'Datto RMM devices (endpoints): lookup, alerts, audit, move, run quick job',
	fields: [],
	operations: [
		{
			value: 'get',
			name: 'Get',
			action: 'Get a device',
			description: 'Retrieve a device by its UID',
			method: 'GET',
			endpoint: '/api/v2/device/{deviceUid}',
			shape: 'object',
			fields: [deviceUid],
		},
		{
			value: 'getByHostname',
			name: 'Get By Hostname',
			action: 'Get a device by hostname',
			description: 'Look up a device by its hostname (case-sensitive). Returns 404 if not found.',
			method: 'GET',
			endpoint: '/api/v2/device/hostname/{hostname}',
			shape: 'object',
			fields: [
				{
					displayName: 'Hostname',
					name: 'hostname',
					type: 'string',
					default: '',
					in: 'path',
					required: true,
					description: 'Exact device hostname',
				},
			],
		},
		{
			value: 'getOpenAlerts',
			name: 'Get Open Alerts',
			action: 'Get open alerts on a device',
			description: 'List open alerts on a specific device',
			method: 'GET',
			endpoint: '/api/v2/device/{deviceUid}/alerts/open',
			shape: 'paginated',
			listKey: 'alerts',
			fields: [deviceUid],
		},
		{
			value: 'getResolvedAlerts',
			name: 'Get Resolved Alerts',
			action: 'Get resolved alerts on a device',
			description: 'List resolved alerts on a specific device',
			method: 'GET',
			endpoint: '/api/v2/device/{deviceUid}/alerts/resolved',
			shape: 'paginated',
			listKey: 'alerts',
			fields: [deviceUid],
		},
		{
			value: 'getAudit',
			name: 'Get Audit',
			action: 'Get device audit log',
			description: 'Retrieve the audit log entries for a specific device',
			method: 'GET',
			endpoint: '/api/v2/audit/device/{deviceUid}',
			shape: 'object',
			fields: [deviceUid],
		},
		{
			value: 'getSoftware',
			name: 'Get Software',
			action: 'Get installed software on a device',
			description: 'List installed software (audit / SWAudit) on a device',
			method: 'GET',
			endpoint: '/api/v2/audit/device/{deviceUid}/software',
			shape: 'paginated',
			listKey: 'software',
			fields: [deviceUid],
		},
		{
			value: 'move',
			name: 'Move',
			action: 'Move a device to a different site',
			description: 'Move a device from its current site to another site',
			method: 'POST',
			endpoint: '/api/v2/device/{deviceUid}/move/site/{siteUid}',
			shape: 'action',
			fields: [
				deviceUid,
				{
					displayName: 'Target Site Name or ID',
					name: 'siteUid',
					type: 'options',
					default: '',
					in: 'path',
					required: true,
					description: 'The destination site UID',
					loadOptionsMethod: 'getSites',
				},
			],
		},
		{
			value: 'setWarranty',
			name: 'Set Warranty',
			action: 'Set device warranty date',
			description: 'Set the warranty expiration date on a device (YYYY-MM-DD)',
			method: 'POST',
			endpoint: '/api/v2/device/{deviceUid}/warranty/{warrantyDate}',
			shape: 'action',
			fields: [
				deviceUid,
				{
					displayName: 'Warranty Date',
					name: 'warrantyDate',
					type: 'string',
					default: '',
					in: 'path',
					required: true,
					description: 'Warranty expiration date in YYYY-MM-DD format',
				},
			],
		},
		{
			value: 'quickJob',
			name: 'Run Quick Job',
			action: 'Run a quick job against a device',
			description: 'Schedule a component (script / monitor) to run against a device as a one-off "quick job". jobName is required.',
			method: 'PUT',
			endpoint: '/api/v2/device/{deviceUid}/quickjob',
			shape: 'object',
			fields: [
				deviceUid,
				{
					displayName: 'Job Name',
					name: 'jobName',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'A label for this quick job execution',
				},
				{
					displayName: 'Component UID',
					name: 'jobComponent',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'The UID of the component (script/monitor) to run',
				},
				{
					displayName: 'Target Device UIDs',
					name: 'targets',
					type: 'json',
					in: 'body',
					description:
						'JSON array of additional target device UIDs (the path device is automatically included)',
					default: '[]',
				},
				{
					displayName: 'Component Variables (JSON)',
					name: 'variables',
					type: 'json',
					in: 'body',
					description:
						'Optional component input variables as JSON object: {"varName":"value", ...}',
					default: '{}',
				},
			],
		},
	],
};
