import type { FieldDescriptor, ResourceDescriptor } from '../types';

const siteUid: FieldDescriptor = {
	displayName: 'Site Name or ID',
	name: 'siteUid',
	type: 'options',
	default: '',
	in: 'path',
	description: 'The Datto RMM site that owns the variable',
	required: true,
	loadOptionsMethod: 'getSites',
};

const variableId: FieldDescriptor = {
	displayName: 'Variable ID',
	name: 'variableId',
	type: 'string',
	default: '',
	in: 'path',
	description: 'The variable ID (numeric). Use Site Variable → Get Many first if you only know the name; this node also exposes an upsert helper that does the lookup for you.',
	required: true,
};

export const siteVariable: ResourceDescriptor = {
	value: 'siteVariable',
	name: 'Site Variable',
	description:
		'Datto RMM site-scoped custom variables. Site variables override account variables of the same name. Hidden variables mask their value in the UI but are still readable via API. Values may be up to 20,000 characters',
	fields: [siteUid],
	operations: [
		{
			value: 'getAll',
			name: 'Get Many',
			action: 'Get many site variables',
			description: 'List all variables defined on a specific site',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}/variables',
			shape: 'list',
			listKey: 'variables',
		},
		{
			value: 'get',
			name: 'Get',
			action: 'Get a site variable',
			description: 'Retrieve a single site variable by its ID',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}/variable/{variableId}',
			shape: 'object',
			fields: [variableId],
		},
		{
			value: 'create',
			name: 'Create',
			action: 'Create a site variable',
			description: 'Create a new site-scoped variable. Datto rejects creation when a variable with the same name already exists on the site — use "Upsert" for idempotent automations.',
			method: 'PUT',
			endpoint: '/api/v2/site/{siteUid}/variable',
			shape: 'object',
			fields: [
				{
					displayName: 'Name',
					name: 'name',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'Variable name (the key, e.g. SITE_COMPANY_NAME). Must be unique on this site.',
				},
				{
					displayName: 'Value',
					name: 'value',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'Variable value (up to 20,000 characters)',
				},
				{
					displayName: 'Masked (Hidden in UI)',
					name: 'masked',
					type: 'boolean',
					in: 'body',
					default: false,
					description: 'Whether to mask the value in the Datto RMM UI. The value is still returned by the API regardless.',
				},
			],
		},
		{
			value: 'update',
			name: 'Update',
			action: 'Update a site variable',
			description: 'Update an existing site variable by ID',
			method: 'POST',
			endpoint: '/api/v2/site/{siteUid}/variable/{variableId}',
			shape: 'object',
			fields: [
				variableId,
				{
					displayName: 'Name',
					name: 'name',
					type: 'string',
					default: '',
					in: 'body',
					description: 'New variable name (rename)',
				},
				{
					displayName: 'Value',
					name: 'value',
					type: 'string',
					default: '',
					in: 'body',
					description: 'New value (up to 20,000 characters)',
				},
				{
					displayName: 'Masked (Hidden in UI)',
					name: 'masked',
					type: 'boolean',
					in: 'body',
					default: false,
					description: 'Whether to mask the value in the Datto RMM UI',
				},
			],
		},
		{
			value: 'delete',
			name: 'Delete',
			action: 'Delete a site variable',
			description: 'Delete a site variable by ID',
			method: 'DELETE',
			endpoint: '/api/v2/site/{siteUid}/variable/{variableId}',
			shape: 'action',
			fields: [variableId],
		},
		{
			value: 'upsert',
			name: 'Create or Update',
			action: 'Upsert a site variable (create or update by name)',
			description: 'Create a new record, or update the current one if it already exists (upsert)',
			method: 'POST',
			endpoint: '/api/v2/site/{siteUid}/variable',
			// Marker shape — engine routes this to a special handler below.
			shape: 'object',
			fields: [
				{
					displayName: 'Name',
					name: 'name',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'Variable name to upsert',
				},
				{
					displayName: 'Value',
					name: 'value',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'Desired variable value',
				},
				{
					displayName: 'Masked (Hidden in UI)',
					name: 'masked',
					type: 'boolean',
					in: 'body',
					default: false,
					description: 'Whether to mask the value in the UI',
				},
			],
		},
	],
};
