import type { FieldDescriptor, ResourceDescriptor } from '../types';

const siteUid: FieldDescriptor = {
	displayName: 'Site Name or ID',
	name: 'siteUid',
	type: 'options',
	default: '',
	in: 'path',
	description:
		'The Datto RMM site (customer). Choose from the list (populated live from /account/sites) or supply a UID via expression. Required for all site-scoped operations.',
	required: true,
	loadOptionsMethod: 'getSites',
};

export const site: ResourceDescriptor = {
	value: 'site',
	name: 'Site',
	description: 'Datto RMM sites (customers): CRUD, devices, alerts, audit, variables',
	fields: [siteUid],
	operations: [
		{
			value: 'get',
			name: 'Get',
			action: 'Get a site',
			description: 'Retrieve a single Datto RMM site by its UID',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}',
			shape: 'object',
		},
		{
			value: 'getDevices',
			name: 'Get Devices',
			action: 'Get many devices on a site',
			description: 'List all devices belonging to a specific site',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}/devices',
			shape: 'paginated',
			listKey: 'devices',
		},
		{
			value: 'getOpenAlerts',
			name: 'Get Open Alerts',
			action: 'Get open alerts on a site',
			description: 'List currently-open alerts on a specific site',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}/alerts/open',
			shape: 'paginated',
			listKey: 'alerts',
		},
		{
			value: 'getResolvedAlerts',
			name: 'Get Resolved Alerts',
			action: 'Get resolved alerts on a site',
			description: 'List resolved alerts on a specific site',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}/alerts/resolved',
			shape: 'paginated',
			listKey: 'alerts',
		},
		{
			value: 'getAudit',
			name: 'Get Audit',
			action: 'Get site audit log',
			description: 'Retrieve the audit log entries for a specific site',
			method: 'GET',
			endpoint: '/api/v2/site/{siteUid}/audit',
			shape: 'paginated',
			listKey: 'auditEntries',
		},
		{
			value: 'create',
			name: 'Create',
			action: 'Create a site',
			description: 'Create a new Datto RMM site (customer). Idempotency by name is NOT enforced — check existence first if running unattended.',
			method: 'PUT',
			endpoint: '/api/v2/site',
			shape: 'object',
			fields: [
				{
					displayName: 'Site Name',
					name: 'name',
					type: 'string',
					default: '',
					in: 'body',
					required: true,
					description: 'The new site name (typically Customer Name - Location)',
				},
				{
					displayName: 'Description',
					name: 'description',
					type: 'string',
					default: '',
					in: 'body',
					description: 'Optional free-text site description',
				},
				{
					displayName: 'Notes',
					name: 'notes',
					type: 'string',
					default: '',
					in: 'body',
					description: 'Operator-facing notes for the site',
				},
				{
					displayName: 'Auto-Join On Install',
					name: 'autoJoinOnInstallEnabled',
					type: 'boolean',
					default: false,
					in: 'body',
					description: 'Whether installed agents auto-join this site',
				},
				{
					displayName: 'Auto-Install Splashtop',
					name: 'splashtopAutoInstall',
					type: 'boolean',
					default: false,
					in: 'body',
					description: 'Whether to auto-install Splashtop on agents at this site',
				},
			],
		},
		{
			value: 'update',
			name: 'Update',
			action: 'Update a site',
			description: 'Update a Datto RMM site',
			method: 'POST',
			endpoint: '/api/v2/site/{siteUid}',
			shape: 'object',
			fields: [
				{
					displayName: 'Site Name',
					name: 'name',
					type: 'string',
					default: '',
					in: 'body',
					description: 'Renamed site title',
				},
				{
					displayName: 'Description',
					name: 'description',
					type: 'string',
					default: '',
					in: 'body',
					description: 'Updated site description',
				},
				{
					displayName: 'Notes',
					name: 'notes',
					type: 'string',
					default: '',
					in: 'body',
					description: 'Updated operator-facing notes',
				},
				{
					displayName: 'Auto-Join On Install',
					name: 'autoJoinOnInstallEnabled',
					type: 'boolean',
					default: false,
					in: 'body',
					description: 'Whether installed agents auto-join this site',
				},
				{
					displayName: 'Auto-Install Splashtop',
					name: 'splashtopAutoInstall',
					type: 'boolean',
					default: false,
					in: 'body',
					description: 'Whether to auto-install Splashtop on agents at this site',
				},
			],
		},
	],
};
